### ISSUE TITLE
Is there an official way to build and/or start app?

### ISSUE THREAD

**Issue by whitestone8214** [willyb321/media_mate#15]
I want to build and use Media Mate, but it seems the description about the way to build and/or start this app is nowhere...
May I request you to write how to build and/or start this app to README.md or somewhere?

**Comment by willyb321** [comment]
Hi! You will need to acquire an API key from [here](https://www.thetvdb.com/) and put it in app/.env as `TVDB_KEY=<key>`.

Then run `yarn install` and `yarn start` and it should boot up.

**Comment by whitestone8214** [comment]
Thank you XD
