### ISSUE TITLE
What happened to the AppImage for Linux?

### ISSUE THREAD

**Issue by probonopd** [willyb321/media_mate#5]
What happened to the AppImage for Linux?

**Comment by willyb321** [comment]
I have not had a chance to upload one in a while. I will be making a release today sometime, I will try to get one up, along with the usual win/macos.

**Comment by willyb321** [comment]
I have uploaded the AppImage. Will close this now, let me know if you have any issues with it.

**Comment by probonopd** [comment]
Thank you very much. Works for me.
